;        1         2         3         4         5         6         7
;234567890123456789012345678901234567890123456789012345678901234567890
;=====================================================================
;
; constants.inc
;
; This header file contains constant symbols.
;
;=====================================================================

; System call numbers
SYSCALL_EXIT    equ    1 ;exit the program

; Program constants
NUM_OF_ELEMENTS equ    5 ;number of elements in the vector
ELEMENTSIZE     equ    4 ;4 bytes (32-bit float, single precision)
